name: First GitHub Action

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: გადმოწერე რეპოზიტორია
        uses: actions/checkout@v3

      - name: დაბეჭდე მესიჯი
        run: echo "გამარჯობა GitHub Actions-დან!"
